(() => {
    "use strict";
    const catalog = {
    "erba-pura": {
        "sku": "PAR-H-001",
        "slug": "erba-pura",
        "nombre": "Erba Pura",
        "marca": "Xerjoff",
        "categoria": "Nicho",
        "genero": "Unisex",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia frutal, luminosa y envolvente. Abre con cítricos mediterráneos, desarrolla un corazón de frutas maduras y termina en una base almizclada, avainillada y ambarada de gran presencia.",
        "familiaOlfativa": "Oriental",
        "anoLanzamiento": 2019,
        "perfumista": "Christian Carbonnel | Laura Santander",
        "notasSalida": "Naranja siciliana | Bergamota de Calabria | Limón siciliano",
        "notasCorazon": "Frutas mediterráneas",
        "notasFondo": "Almizcle blanco | Vainilla de Madagascar | Ámbar",
        "acordesPrincipales": "Frutal | Dulce | Cítrico | Almizclado | Avainillado | Ambarado",
        "duracion": "10–12 horas",
        "proyeccion": "Alta durante 3–4 horas; estela marcada",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Salidas | Reuniones | Ocasiones especiales",
        "estilo": "Lujoso, frutal y llamativo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Xerjoff/Erba-Pura-55157.html"
    },
    "torino-21": {
        "sku": "PAR-H-002",
        "slug": "torino-21",
        "nombre": "Torino 21",
        "marca": "Xerjoff",
        "categoria": "Nicho",
        "genero": "Unisex",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una composición verde y enérgica construida alrededor de menta, cítricos y hierbas aromáticas. Su evolución conserva una sensación limpia, deportiva y refinada.",
        "familiaOlfativa": "Aromática Verde",
        "anoLanzamiento": 2021,
        "perfumista": "",
        "notasSalida": "Menta | Limón | Albahaca | Tomillo",
        "notasCorazon": "Grosella negra | Lavanda | Romero | Jazmín",
        "notasFondo": "Almizcle | Hierba luisa",
        "acordesPrincipales": "Verde | Aromático | Fresco especiado | Cítrico | Herbal",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada a alta durante 2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Diario | Oficina | Actividades al aire libre",
        "estilo": "Fresco, deportivo y sofisticado",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Xerjoff/Torino21-70424.html"
    },
    "invictus-victory-elixir": {
        "sku": "PAR-H-003",
        "slug": "invictus-victory-elixir",
        "nombre": "Invictus Victory Elixir",
        "marca": "Paco Rabanne",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Elixir",
        "descripcion": "Un elixir oscuro y potente que combina especias, lavanda aromática, incienso y una base cremosa de vainilla y haba tonka. Está pensado para destacar en noches y climas frescos.",
        "familiaOlfativa": "Oriental Amaderada",
        "anoLanzamiento": 2023,
        "perfumista": "Domitille Michalon Bertier | Anne Flipo | Nicolas Beaulieu",
        "notasSalida": "Lavanda | Cardamomo | Pimienta negra",
        "notasCorazon": "Incienso | Pachulí",
        "notasFondo": "Vainilla | Haba tonka",
        "acordesPrincipales": "Avainillado | Cálido especiado | Ambarado | Aromático | Ahumado",
        "duracion": "9–12 horas",
        "proyeccion": "Alta durante 3 horas; estela intensa",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Noche | Citas | Fiestas",
        "estilo": "Dulce, oscuro y seductor",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Rabanne/Invictus-Victory-Elixir-78575.html"
    },
    "stronger-with-you-intensely": {
        "sku": "PAR-H-004",
        "slug": "stronger-with-you-intensely",
        "nombre": "Stronger With You Intensely",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia cálida y adictiva con pimienta rosada, toffee, canela y vainilla. Su perfil dulce y especiado funciona especialmente bien en ambientes frescos y ocasiones nocturnas.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 2019,
        "perfumista": "",
        "notasSalida": "Pimienta rosa | Enebro | Violeta",
        "notasCorazon": "Toffee | Canela | Lavanda | Salvia",
        "notasFondo": "Vainilla | Ámbar | Haba tonka | Ante",
        "acordesPrincipales": "Dulce | Avainillado | Cálido especiado | Canela | Ambarado",
        "duracion": "9–11 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Noche | Eventos",
        "estilo": "Cálido, juvenil y envolvente",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Emporio-Armani-Stronger-With-You-Intensely-52802.html"
    },
    "valentino-uomo-born-in-roma-intense": {
        "sku": "PAR-H-005",
        "slug": "valentino-uomo-born-in-roma-intense",
        "nombre": "Valentino Uomo Born in Roma Intense",
        "marca": "Valentino",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum Intense",
        "descripcion": "Una interpretación intensa y nocturna del ADN Born in Roma. La vainilla aporta dulzor, la lavanda equilibra el perfil y el vetiver añade una base seca y elegante.",
        "familiaOlfativa": "Oriental Vainilla",
        "anoLanzamiento": 2023,
        "perfumista": "",
        "notasSalida": "Vainilla",
        "notasCorazon": "Lavanda",
        "notasFondo": "Vetiver",
        "acordesPrincipales": "Avainillado | Aromático | Lavanda | Amaderado | Dulce",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada a alta durante 2 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Citas | Salidas nocturnas | Eventos",
        "estilo": "Moderno, dulce y elegante",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Valentino/Valentino-Uomo-Born-In-Roma-Intense-78740.html"
    },
    "dior-homme-intense": {
        "sku": "PAR-H-006",
        "slug": "dior-homme-intense",
        "nombre": "Dior Homme Intense",
        "marca": "Christian Dior",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum Intense",
        "descripcion": "Una fragancia elegante de iris con una textura empolvada y ligeramente dulce. La pera y la ambreta suavizan el corazón, mientras cedro y vetiver dejan un fondo sobrio.",
        "familiaOlfativa": "Floral Amaderada Almizclada",
        "anoLanzamiento": 2011,
        "perfumista": "François Demachy",
        "notasSalida": "Lavanda",
        "notasCorazon": "Iris | Ambreta | Pera",
        "notasFondo": "Cedro de Virginia | Vetiver",
        "acordesPrincipales": "Iris | Empolvado | Floral | Amaderado | Violeta",
        "duracion": "8–10 horas",
        "proyeccion": "Moderada a alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Formal | Citas | Eventos elegantes",
        "estilo": "Refinado, empolvado y sofisticado",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Dior/Dior-Homme-Intense-2011-13016.html"
    },
    "armani-code-parfum": {
        "sku": "PAR-H-007",
        "slug": "armani-code-parfum",
        "nombre": "Armani Code Parfum",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum",
        "descripcion": "Una propuesta limpia y elegante en la que la bergamota se encuentra con iris, salvia y una base de haba tonka y cedro. Tiene un carácter formal sin resultar pesado.",
        "familiaOlfativa": "Amaderada Aromática",
        "anoLanzamiento": 2022,
        "perfumista": "Antoine Maisondieu",
        "notasSalida": "Bergamota | Hoja de bergamota",
        "notasCorazon": "Iris | Raíz de lirio | Salvia esclarea",
        "notasFondo": "Haba tonka | Cedro",
        "acordesPrincipales": "Iris | Aromático | Amaderado | Cítrico | Atalcado",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Oficina | Formal | Citas",
        "estilo": "Limpio, elegante y versátil",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Armani-Code-Parfum-75126.html"
    },
    "one-million-elixir": {
        "sku": "PAR-H-008",
        "slug": "one-million-elixir",
        "nombre": "One Million Elixir",
        "marca": "Paco Rabanne",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Elixir",
        "descripcion": "Una composición dulce y densa con manzana, davana, rosa, vainilla y haba tonka. La base amaderada y de pachulí aporta profundidad a su perfil gourmand.",
        "familiaOlfativa": "Amaderada Aromática",
        "anoLanzamiento": 2022,
        "perfumista": "",
        "notasSalida": "Manzana | Davana",
        "notasCorazon": "Rosa de Damasco | Cedro | Osmanto",
        "notasFondo": "Absoluto de vainilla | Haba tonka | Pachulí",
        "acordesPrincipales": "Avainillado | Dulce | Frutal | Amaderado | Rosado",
        "duracion": "9–12 horas",
        "proyeccion": "Alta durante 3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Fiestas | Citas | Noche",
        "estilo": "Opulento, dulce y llamativo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Paco-Rabanne/1-Million-Elixir-71708.html"
    },
    "acqua-di-gio-parfum": {
        "sku": "PAR-H-009",
        "slug": "acqua-di-gio-parfum",
        "nombre": "Acqua di Giò Parfum",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum",
        "descripcion": "Una fragancia marina refinada que combina bergamota, notas acuáticas, hierbas aromáticas, incienso y pachulí. Mantiene frescura, pero con un fondo más oscuro y elegante.",
        "familiaOlfativa": "Amaderada Acuática",
        "anoLanzamiento": 2023,
        "perfumista": "Alberto Morillas",
        "notasSalida": "Notas marinas | Bergamota",
        "notasCorazon": "Romero | Salvia esclarea | Geranio",
        "notasFondo": "Incienso | Pachulí",
        "acordesPrincipales": "Marino | Aromático | Fresco especiado | Amaderado | Ahumado",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada durante 2–3 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Oficina | Diario | Cena",
        "estilo": "Marino, elegante y contemporáneo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Acqua-di-Gio-Parfum-81508.html"
    },
    "y-eau-de-parfum": {
        "sku": "PAR-H-010",
        "slug": "y-eau-de-parfum",
        "nombre": "Y Eau de Parfum",
        "marca": "Yves Saint Laurent (YSL)",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una aromática moderna que abre con manzana, jengibre y bergamota. Salvia y enebro construyen un corazón limpio, mientras maderas ambaradas y haba tonka aportan cuerpo.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2018,
        "perfumista": "Dominique Ropion | Claire Liegent",
        "notasSalida": "Manzana | Jengibre | Bergamota",
        "notasCorazon": "Salvia | Enebro | Geranio",
        "notasFondo": "Amberwood | Haba tonka | Cedro | Vetiver | Incienso",
        "acordesPrincipales": "Aromático | Fresco especiado | Amaderado | Frutal | Ámbar",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada a alta durante 2–3 horas",
        "estaciones": "Todo el año",
        "ocasiones": "Oficina | Diario | Noche casual",
        "estilo": "Limpio, moderno y versátil",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html"
    },
    "the-most-wanted-parfum": {
        "sku": "PAR-H-011",
        "slug": "the-most-wanted-parfum",
        "nombre": "The Most Wanted Parfum",
        "marca": "Azzaro",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum",
        "descripcion": "Una fragancia de estructura sencilla pero intensa: jengibre especiado, un corazón amaderado y vainilla bourbon. El resultado es cálido, dulce y muy nocturno.",
        "familiaOlfativa": "Oriental Especiada",
        "anoLanzamiento": 2022,
        "perfumista": "",
        "notasSalida": "Jengibre",
        "notasCorazon": "Notas amaderadas",
        "notasFondo": "Vainilla bourbon",
        "acordesPrincipales": "Avainillado | Cálido especiado | Amaderado | Dulce",
        "duracion": "9–11 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Fiesta | Noche",
        "estilo": "Seductor, cálido e intenso",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Azzaro/The-Most-Wanted-Parfum-73664.html"
    },
    "sauvage-eau-de-parfum": {
        "sku": "PAR-H-012",
        "slug": "sauvage-eau-de-parfum",
        "nombre": "Sauvage Eau de Parfum",
        "marca": "Christian Dior",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Bergamota brillante, especias, lavanda, ambroxan y vainilla forman una fragancia reconocible, masculina y de amplio rendimiento.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 2018,
        "perfumista": "François Demachy",
        "notasSalida": "Bergamota",
        "notasCorazon": "Pimienta de Sichuan | Lavanda | Anís estrellado | Nuez moscada",
        "notasFondo": "Ambroxan | Vainilla",
        "acordesPrincipales": "Fresco especiado | Ámbar | Aromático | Cítrico | Lavanda",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Todo el año",
        "ocasiones": "Diario | Noche | Eventos",
        "estilo": "Masculino, limpio y potente",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Dior/Sauvage-Eau-de-Parfum-48100.html"
    },
    "le-male-elixir": {
        "sku": "PAR-H-013",
        "slug": "le-male-elixir",
        "nombre": "Le Male Elixir",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Elixir",
        "descripcion": "Una mezcla intensa de lavanda y menta sobre un corazón de vainilla y benjuí. Miel, tabaco y haba tonka construyen un fondo dulce, cálido y persistente.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 2023,
        "perfumista": "Quentin Bisch",
        "notasSalida": "Lavanda | Menta",
        "notasCorazon": "Vainilla | Benjuí",
        "notasFondo": "Miel | Haba tonka | Tabaco",
        "acordesPrincipales": "Dulce | Avainillado | Miel | Tabaco | Ambarado",
        "duracion": "9–12 horas",
        "proyeccion": "Alta durante 3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Fiestas | Noche",
        "estilo": "Dulce, sensual y potente",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-81642.html"
    },
    "le-beau-le-parfum": {
        "sku": "PAR-H-014",
        "slug": "le-beau-le-parfum",
        "nombre": "Le Beau Le Parfum",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Le Parfum",
        "descripcion": "Una fragancia tropical y oscura con piña, coco, iris y jengibre, apoyada sobre tonka, sándalo y ámbar. Dulce, cremosa y orientada a la noche.",
        "familiaOlfativa": "Oriental Amaderada",
        "anoLanzamiento": 2022,
        "perfumista": "Quentin Bisch",
        "notasSalida": "Piña | Iris | Jengibre | Ciprés",
        "notasCorazon": "Coco | Notas amaderadas",
        "notasFondo": "Haba tonka | Sándalo | Ámbar | Ámbar gris",
        "acordesPrincipales": "Coco | Dulce | Amaderado | Tropical | Avainillado",
        "duracion": "8–10 horas",
        "proyeccion": "Moderada a alta durante 2–3 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Citas | Vacaciones | Noche",
        "estilo": "Tropical, cremoso y seductor",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Le-Beau-Le-Parfum-72158.html"
    },
    "eros-flame-eau-de-parfum": {
        "sku": "PAR-H-015",
        "slug": "eros-flame-eau-de-parfum",
        "nombre": "Eros Flame Eau de Parfum",
        "marca": "Versace",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una salida cítrica y picante da paso a geranio y rosa, antes de asentarse en vainilla, tonka, sándalo y maderas. Es cálida, expresiva y de buena presencia.",
        "familiaOlfativa": "Amaderada Especiada",
        "anoLanzamiento": 2018,
        "perfumista": "Olivier Pescheux",
        "notasSalida": "Mandarina | Pimienta negra | Limón | Chinotto | Romero",
        "notasCorazon": "Geranio | Rosa | Pepperwood",
        "notasFondo": "Vainilla | Haba tonka | Sándalo | Cedro | Pachulí | Musgo",
        "acordesPrincipales": "Cítrico | Cálido especiado | Avainillado | Aromático | Amaderado",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Noche | Citas | Eventos",
        "estilo": "Enérgico, cálido y masculino",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Versace/Eros-Flame-52180.html"
    },
    "french-riviera": {
        "sku": "PAR-H-016",
        "slug": "french-riviera",
        "nombre": "French Riviera",
        "marca": "Mancera",
        "categoria": "Nicho",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una interpretación luminosa de la costa mediterránea. Cítricos, jengibre y pimienta se mezclan con notas marinas, flores solares, sal, almizcle y ámbar.",
        "familiaOlfativa": "Aromática Acuática",
        "anoLanzamiento": 2022,
        "perfumista": "Pierre Montale",
        "notasSalida": "Naranja | Limón | Mandarina | Jengibre | Pimienta",
        "notasCorazon": "Notas marinas | Flor de tiaré | Mimosa | Pino",
        "notasFondo": "Sal marina | Almizcle blanco | Ámbar",
        "acordesPrincipales": "Marino | Cítrico | Salado | Aromático | Floral",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Playa | Vacaciones | Diario",
        "estilo": "Fresco, salino y vacacional",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Mancera/French-Riviera-74636.html"
    },
    "invictus-victory-eau-de-parfum": {
        "sku": "PAR-H-017",
        "slug": "invictus-victory-eau-de-parfum",
        "nombre": "Invictus Victory Eau de Parfum",
        "marca": "Paco Rabanne",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia oriental que contrasta limón y pimienta rosada con incienso, lavanda, vainilla, tonka y ámbar. Dulce y ahumada, pensada para la noche.",
        "familiaOlfativa": "Oriental",
        "anoLanzamiento": 2021,
        "perfumista": "",
        "notasSalida": "Pimienta rosa | Limón",
        "notasCorazon": "Incienso | Lavanda",
        "notasFondo": "Vainilla | Haba tonka | Ámbar",
        "acordesPrincipales": "Avainillado | Ambarado | Cálido especiado | Ahumado | Aromático",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Noche | Citas | Fiesta",
        "estilo": "Dulce, ahumado y poderoso",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Rabanne/Invictus-Victory-65177.html"
    },
    "scandal-pour-homme-le-parfum": {
        "sku": "PAR-H-018",
        "slug": "scandal-pour-homme-le-parfum",
        "nombre": "Scandal Pour Homme Le Parfum",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Le Parfum",
        "descripcion": "Una composición dulce y amaderada centrada en geranio aromático, haba tonka y sándalo. Tiene un carácter cremoso, nocturno y seductor.",
        "familiaOlfativa": "Oriental",
        "anoLanzamiento": 2022,
        "perfumista": "",
        "notasSalida": "Geranio",
        "notasCorazon": "Haba tonka",
        "notasFondo": "Sándalo",
        "acordesPrincipales": "Dulce | Avainillado | Amaderado | Aromático | Cálido especiado",
        "duracion": "8–10 horas",
        "proyeccion": "Moderada a alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Noche | Fiesta",
        "estilo": "Cremoso, dulce y sensual",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Scandal-Pour-Homme-Le-Parfum-71772.html"
    },
    "valentino-uomo-born-in-roma-eau-de-toilette": {
        "sku": "PAR-H-019",
        "slug": "valentino-uomo-born-in-roma-eau-de-toilette",
        "nombre": "Valentino Uomo Born in Roma Eau de Toilette",
        "marca": "Valentino",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una fragancia urbana que mezcla notas minerales y saladas con hoja de violeta, jengibre, salvia, vetiver y maderas. Fresca, especiada y fácil de usar.",
        "familiaOlfativa": "Amaderada Especiada",
        "anoLanzamiento": 2019,
        "perfumista": "",
        "notasSalida": "Notas minerales | Hoja de violeta | Sal",
        "notasCorazon": "Jengibre | Salvia",
        "notasFondo": "Notas amaderadas | Vetiver",
        "acordesPrincipales": "Mineral | Aromático | Fresco especiado | Amaderado | Violeta",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Diario | Universidad | Oficina",
        "estilo": "Urbano, fresco y juvenil",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Valentino/Valentino-Uomo-Born-In-Roma-55963.html"
    },
    "valentino-uomo-born-in-roma-coral-fantasy": {
        "sku": "PAR-H-020",
        "slug": "valentino-uomo-born-in-roma-coral-fantasy",
        "nombre": "Valentino Uomo Born in Roma Coral Fantasy",
        "marca": "Valentino",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Manzana roja y cardamomo abren una fragancia dulce y aromática. Lavanda y salvia conducen a un fondo de tabaco, pachulí y vetiver.",
        "familiaOlfativa": "Aromática Frutal",
        "anoLanzamiento": 2022,
        "perfumista": "",
        "notasSalida": "Manzana roja | Cardamomo | Bergamota de Calabria",
        "notasCorazon": "Lavanda | Geranio bourbon | Salvia esclarea",
        "notasFondo": "Hoja de tabaco | Pachulí | Vetiver",
        "acordesPrincipales": "Frutal | Cálido especiado | Aromático | Tabaco | Amaderado",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada a alta durante 2 horas",
        "estaciones": "Otoño | Primavera | Invierno",
        "ocasiones": "Citas | Noche casual | Salidas",
        "estilo": "Juvenil, frutal y atractivo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Valentino/Valentino-Uomo-Born-In-Roma-Coral-Fantasy-71761.html"
    },
    "valentino-uomo-born-in-roma-green-stravaganza": {
        "sku": "PAR-H-021",
        "slug": "valentino-uomo-born-in-roma-green-stravaganza",
        "nombre": "Valentino Uomo Born in Roma Green Stravaganza",
        "marca": "Valentino",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una combinación moderna de bergamota, café y vetiver. Empieza brillante, desarrolla un matiz tostado y termina en un fondo verde y seco.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 2024,
        "perfumista": "Nathalie Lorson | Olivier Cresp",
        "notasSalida": "Bergamota de Calabria",
        "notasCorazon": "Café",
        "notasFondo": "Vetiver",
        "acordesPrincipales": "Cítrico | Café | Aromático | Amaderado | Verde",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Diario | Oficina | Salidas casuales",
        "estilo": "Verde, moderno y original",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Valentino/Valentino-Uomo-Born-In-Roma-Green-Stravaganza-89969.html"
    },
    "one-million-parfum": {
        "sku": "PAR-H-022",
        "slug": "one-million-parfum",
        "nombre": "One Million Parfum",
        "marca": "Paco Rabanne",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum",
        "descripcion": "Una propuesta solar y salada con tuberosa, monoi, ámbar, cuero y maderas. Es floral, cálida y diferente dentro de la línea 1 Million.",
        "familiaOlfativa": "Cuero Floral",
        "anoLanzamiento": 2020,
        "perfumista": "Quentin Bisch | Christophe Raynaud",
        "notasSalida": "Notas solares | Sal",
        "notasCorazon": "Tuberosa | Aceite de monoi",
        "notasFondo": "Cuero | Ámbar | Cashmeran | Pino",
        "acordesPrincipales": "Floral blanco | Salado | Solar | Cuero | Ambarado",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Fiestas | Vacaciones | Noche",
        "estilo": "Solar, floral y extravagante",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Paco-Rabanne/1-Million-Parfum-60035.html"
    },
    "prada-luna-rossa-ocean-eau-de-toilette": {
        "sku": "PAR-H-023",
        "slug": "prada-luna-rossa-ocean-eau-de-toilette",
        "nombre": "Prada Luna Rossa Ocean Eau de Toilette",
        "marca": "Prada",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una fougère moderna que combina bergamota, pimienta rosa y artemisa con lavanda, iris, salvia, ante, azafrán, vetiver y almizcle.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2021,
        "perfumista": "Anne Flipo | Carlos Benaim",
        "notasSalida": "Bergamota | Pimienta rosa | Artemisa",
        "notasCorazon": "Lavanda | Iris | Salvia | Ante | Azafrán",
        "notasFondo": "Almizcle | Caramelo | Vetiver de Haití | Pachulí",
        "acordesPrincipales": "Aromático | Lavanda | Fresco especiado | Amaderado | Iris",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Oficina | Diario | Universidad",
        "estilo": "Limpio, moderno y pulido",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Prada/Luna-Rossa-Ocean-68753.html"
    },
    "million-gold": {
        "sku": "PAR-H-024",
        "slug": "million-gold",
        "nombre": "One Million Gold",
        "marca": "Paco Rabanne",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum Intense",
        "descripcion": "Una fragancia amaderada y especiada que une mandarina luminosa, especias, cedro y sándalo. Tiene un perfil cálido, limpio y de presencia marcada.",
        "familiaOlfativa": "Amaderada Aromática",
        "anoLanzamiento": 2024,
        "perfumista": "Quentin Bisch",
        "notasSalida": "Mandarina",
        "notasCorazon": "Especias | Cedro",
        "notasFondo": "Sándalo",
        "acordesPrincipales": "Amaderado | Cálido especiado | Cítrico | Aromático",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada a alta durante 2 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Eventos | Noche | Salidas",
        "estilo": "Brillante, amaderado y moderno",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Rabanne/Million-Gold-92627.html"
    },
    "acqua-di-gio-eau-de-parfum": {
        "sku": "PAR-H-025",
        "slug": "acqua-di-gio-eau-de-parfum",
        "nombre": "Acqua di Giò Eau de Parfum",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una versión verde y marina con mandarina, salvia, lavanda, geranio, notas minerales, vetiver y pachulí. Fresca, natural y versátil.",
        "familiaOlfativa": "Aromática Acuática",
        "anoLanzamiento": 2022,
        "perfumista": "Alberto Morillas",
        "notasSalida": "Notas marinas | Mandarina verde",
        "notasCorazon": "Salvia esclarea | Lavanda | Geranio",
        "notasFondo": "Notas minerales | Vetiver | Pachulí",
        "acordesPrincipales": "Marino | Aromático | Verde | Fresco especiado | Cítrico",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Oficina | Diario | Clima cálido",
        "estilo": "Natural, fresco y elegante",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Acqua-di-Gio-Eau-de-Parfum-71606.html"
    },
    "acqua-di-gio-profondo-parfum": {
        "sku": "PAR-H-026",
        "slug": "acqua-di-gio-profondo-parfum",
        "nombre": "Acqua di Giò Profondo Parfum",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum",
        "descripcion": "Una interpretación más profunda del perfil marino de Profondo, con cítricos, notas acuáticas, facetas aromáticas y un fondo mineral y amaderado.",
        "familiaOlfativa": "Aromática Acuática",
        "anoLanzamiento": 2024,
        "perfumista": "Alberto Morillas",
        "notasSalida": "Notas marinas | Mandarina verde | Cardamomo",
        "notasCorazon": "Mimosa | Notas aromáticas",
        "notasFondo": "Notas minerales | Pachulí",
        "acordesPrincipales": "Marino | Aromático | Mineral | Fresco especiado | Amaderado",
        "duracion": "7–9 horas",
        "proyeccion": "Moderada durante 2–3 horas",
        "estaciones": "Primavera | Verano | Otoño",
        "ocasiones": "Oficina | Diario | Cena",
        "estilo": "Marino, profundo y refinado",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Acqua-di-Gio-Profondo-Parfum-90625.html"
    },
    "acqua-di-gio-profondo-eau-de-parfum": {
        "sku": "PAR-H-027",
        "slug": "acqua-di-gio-profondo-eau-de-parfum",
        "nombre": "Acqua di Giò Profondo Eau de Parfum",
        "marca": "Giorgio Armani",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia marina y mineral con Aquozone, bergamota, mandarina, romero, lavanda, ciprés y un fondo de almizcle, pachulí y ámbar.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2020,
        "perfumista": "Alberto Morillas",
        "notasSalida": "Notas marinas | Aquozone | Bergamota | Mandarina verde",
        "notasCorazon": "Romero | Lavanda | Ciprés | Lentisco",
        "notasFondo": "Notas minerales | Almizcle | Pachulí | Ámbar",
        "acordesPrincipales": "Marino | Aromático | Fresco especiado | Mineral | Cítrico",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Diario | Oficina | Playa",
        "estilo": "Acuático, limpio y profundo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Giorgio-Armani/Acqua-di-Gio-Profondo-59532.html"
    },
    "myslf-eau-de-parfum": {
        "sku": "PAR-H-028",
        "slug": "myslf-eau-de-parfum",
        "nombre": "MYSLF Eau de Parfum",
        "marca": "Yves Saint Laurent (YSL)",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia limpia y contemporánea: bergamota brillante, flor de azahar y una base de Ambrofix y pachulí. Floral sin perder un carácter masculino y versátil.",
        "familiaOlfativa": "Aromática",
        "anoLanzamiento": 2023,
        "perfumista": "Daniela Andrier | Antoine Maisondieu | Christophe Raynaud",
        "notasSalida": "Bergamota de Calabria | Bergamota",
        "notasCorazon": "Flor de azahar de Túnez",
        "notasFondo": "Ambrofix | Pachulí",
        "acordesPrincipales": "Cítrico | Floral blanco | Aromático | Ambarado | Fresco",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Todo el año",
        "ocasiones": "Oficina | Diario | Citas casuales",
        "estilo": "Limpio, minimalista y moderno",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Yves-Saint-Laurent/MYSLF-Eau-de-Parfum-83248.html"
    },
    "the-most-wanted-eau-de-parfum-intense": {
        "sku": "PAR-H-029",
        "slug": "the-most-wanted-eau-de-parfum-intense",
        "nombre": "The Most Wanted Eau de Parfum Intense",
        "marca": "Azzaro",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum Intense",
        "descripcion": "Cardamomo, toffee y amberwood forman una fragancia gourmand de estructura directa. Es dulce, especiada y especialmente efectiva en clima fresco.",
        "familiaOlfativa": "Oriental Especiada",
        "anoLanzamiento": 2021,
        "perfumista": "Michel Girard | Nadège Le Garlantezec | Shyamala Maisondieu",
        "notasSalida": "Cardamomo",
        "notasCorazon": "Toffee",
        "notasFondo": "Amberwood",
        "acordesPrincipales": "Cálido especiado | Caramelo | Ambarado | Dulce",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Noche | Fiesta",
        "estilo": "Gourmand, cálido y seductor",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Azzaro/The-Most-Wanted-66826.html"
    },
    "sauvage-eau-de-toilette": {
        "sku": "PAR-H-030",
        "slug": "sauvage-eau-de-toilette",
        "nombre": "Sauvage Eau de Toilette",
        "marca": "Christian Dior",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una aromática fresca y expansiva con bergamota, pimientas, lavanda, vetiver, pachulí, cedro y ambroxan. Versátil, reconocible y de fuerte salida.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2015,
        "perfumista": "François Demachy",
        "notasSalida": "Bergamota de Calabria | Pimienta",
        "notasCorazon": "Pimienta de Sichuan | Lavanda | Pimienta rosa | Vetiver | Pachulí | Geranio | Elemí",
        "notasFondo": "Ambroxan | Cedro | Ládano",
        "acordesPrincipales": "Fresco especiado | Ámbar | Aromático | Cítrico | Amaderado",
        "duracion": "7–9 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Todo el año",
        "ocasiones": "Diario | Oficina | Noche",
        "estilo": "Fresco, expansivo y masculino",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Dior/Sauvage-31861.html"
    },
    "sauvage-eau-forte": {
        "sku": "PAR-H-031",
        "slug": "sauvage-eau-forte",
        "nombre": "Sauvage Eau Forte",
        "marca": "Christian Dior",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau Forte sin alcohol",
        "descripcion": "Una interpretación acuosa y especiada de Sauvage. Especias y elemí abren el perfume, la lavanda ocupa el centro y un fondo almizclado y amaderado aporta suavidad.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2024,
        "perfumista": "Francis Kurkdjian",
        "notasSalida": "Especias | Elemí",
        "notasCorazon": "Lavanda",
        "notasFondo": "Almizcle | Notas amaderadas",
        "acordesPrincipales": "Aromático | Fresco especiado | Lavanda | Almizclado | Amaderado",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Diario | Oficina | Clima cálido",
        "estilo": "Suave, fresco y cremoso",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Dior/Sauvage-Eau-Forte-94761.html"
    },
    "le-male-elixir-absolu": {
        "sku": "PAR-H-032",
        "slug": "le-male-elixir-absolu",
        "nombre": "Le Male Elixir Absolu",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Parfum Intense",
        "descripcion": "Una evolución frutal y licorosa del perfil Le Male, con ciruela, lavanda y haba tonka. Dulce, cálida y orientada a noches de clima fresco.",
        "familiaOlfativa": "Oriental Especiada",
        "anoLanzamiento": 2025,
        "perfumista": "Quentin Bisch",
        "notasSalida": "Ciruela",
        "notasCorazon": "Lavanda | Davana",
        "notasFondo": "Haba tonka | Benjuí",
        "acordesPrincipales": "Frutal | Dulce | Avainillado | Aromático | Ambarado",
        "duracion": "8–10 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Fiesta | Noche",
        "estilo": "Licoroso, dulce y magnético",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Le-Male-Elixir-Absolu-101529.html"
    },
    "le-male-le-parfum": {
        "sku": "PAR-H-033",
        "slug": "le-male-le-parfum",
        "nombre": "Le Male Le Parfum",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum Intense",
        "descripcion": "Cardamomo especiado abre una composición de lavanda e iris, seguida por un fondo de vainilla y maderas orientales. Su carácter es elegante, cálido y nocturno.",
        "familiaOlfativa": "Oriental",
        "anoLanzamiento": 2020,
        "perfumista": "Quentin Bisch | Natalie Gracia-Cetto",
        "notasSalida": "Cardamomo",
        "notasCorazon": "Lavanda | Iris",
        "notasFondo": "Vainilla | Notas orientales | Notas amaderadas",
        "acordesPrincipales": "Avainillado | Aromático | Cálido especiado | Lavanda | Iris",
        "duracion": "8–10 horas",
        "proyeccion": "Moderada a alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Citas | Formal | Noche",
        "estilo": "Elegante, cremoso y seductor",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Le-Male-Le-Parfum-61856.html"
    },
    "ultra-male": {
        "sku": "PAR-H-034",
        "slug": "ultra-male",
        "nombre": "Ultra Male",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette Intense",
        "descripcion": "Pera, menta y cítricos dan una salida jugosa; canela y salvia aportan especias, y vainilla negra, ámbar y maderas crean un fondo muy dulce y persistente.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 2015,
        "perfumista": "Francis Kurkdjian",
        "notasSalida": "Pera | Lavanda | Menta | Bergamota | Limón",
        "notasCorazon": "Canela | Salvia esclarea | Alcaravea",
        "notasFondo": "Vainilla negra | Ámbar | Pachulí | Cedro",
        "acordesPrincipales": "Dulce | Frutal | Avainillado | Canela | Aromático",
        "duracion": "9–12 horas",
        "proyeccion": "Alta durante 3–4 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Fiesta | Noche | Citas",
        "estilo": "Juvenil, dulce y explosivo",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Ultra-Male-30947.html"
    },
    "le-male-eau-de-toilette": {
        "sku": "PAR-H-035",
        "slug": "le-male-eau-de-toilette",
        "nombre": "Le Male Eau de Toilette",
        "marca": "Jean Paul Gaultier",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Un clásico fougère oriental: menta, lavanda y cardamomo se combinan con canela, flor de azahar, vainilla, tonka, ámbar y sándalo.",
        "familiaOlfativa": "Oriental Fougère",
        "anoLanzamiento": 1995,
        "perfumista": "Francis Kurkdjian",
        "notasSalida": "Lavanda | Menta | Cardamomo | Bergamota | Artemisa",
        "notasCorazon": "Canela | Flor de azahar | Alcaravea",
        "notasFondo": "Vainilla | Haba tonka | Ámbar | Sándalo | Cedro",
        "acordesPrincipales": "Aromático | Avainillado | Lavanda | Cálido especiado | Fresco",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada a alta durante 2 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Diario | Noche casual | Citas",
        "estilo": "Clásico, limpio y sensual",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Jean-Paul-Gaultier/Le-Male-430.html"
    },
    "eros-eau-de-parfum": {
        "sku": "PAR-H-036",
        "slug": "eros-eau-de-parfum",
        "nombre": "Eros Eau de Parfum",
        "marca": "Versace",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Menta, manzana acaramelada y cítricos abren una fragancia intensa. Ambroxan, geranio, vainilla, cedro, sándalo y cuero aportan dulzor y profundidad.",
        "familiaOlfativa": "Oriental Amaderada",
        "anoLanzamiento": 2020,
        "perfumista": "",
        "notasSalida": "Menta | Manzana acaramelada | Limón | Mandarina",
        "notasCorazon": "Ambroxan | Geranio | Salvia esclarea",
        "notasFondo": "Vainilla | Cedro | Sándalo | Naranja amarga | Pachulí | Cuero",
        "acordesPrincipales": "Avainillado | Aromático | Fresco especiado | Verde | Dulce",
        "duracion": "7–9 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Fiesta | Noche | Citas",
        "estilo": "Potente, dulce y energético",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Versace/Eros-Eau-de-Parfum-66236.html"
    },
    "polo-red-eau-de-parfum": {
        "sku": "PAR-H-037",
        "slug": "polo-red-eau-de-parfum",
        "nombre": "Polo Red Eau de Parfum",
        "marca": "Ralph Lauren",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Arándano, jengibre y pomelo crean una salida vibrante. Lavanda y salvia dan estructura, mientras resinas, cedro, almizcle y madera de gaiac aportan calidez.",
        "familiaOlfativa": "Amaderada Especiada",
        "anoLanzamiento": 2020,
        "perfumista": "",
        "notasSalida": "Arándano | Jengibre | Pomelo rosado",
        "notasCorazon": "Salvia esclarea | Lavanda | Ládano",
        "notasFondo": "Opopónaco | Benjuí | Cedro | Almizcle | Madera de gaiac",
        "acordesPrincipales": "Fresco especiado | Aromático | Frutal | Ambarado | Amaderado",
        "duracion": "6–8 horas",
        "proyeccion": "Moderada durante 2 horas",
        "estaciones": "Otoño | Primavera | Invierno",
        "ocasiones": "Diario | Noche casual | Salidas",
        "estilo": "Energético, especiado y versátil",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Ralph-Lauren/Polo-Red-Eau-de-Parfum-65773.html"
    },
    "polo-blue-eau-de-parfum": {
        "sku": "PAR-H-038",
        "slug": "polo-blue-eau-de-parfum",
        "nombre": "Polo Blue Eau de Parfum",
        "marca": "Ralph Lauren",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fragancia azul y aromática con notas marinas, bergamota, cardamomo, albahaca, iris, salvia, vetiver, ante, pachulí y maderas.",
        "familiaOlfativa": "Amaderada Aromática",
        "anoLanzamiento": 2016,
        "perfumista": "Carlos Benaim",
        "notasSalida": "Notas marinas | Bergamota | Cardamomo",
        "notasCorazon": "Albahaca | Verbena | Salvia esclarea | Iris",
        "notasFondo": "Ante | Vetiver | Notas amaderadas | Pachulí",
        "acordesPrincipales": "Aromático | Marino | Fresco especiado | Amaderado | Verde",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Oficina | Diario | Fin de semana",
        "estilo": "Fresco, limpio y relajado",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Ralph-Lauren/Polo-Blue-Eau-de-Parfum-40484.html"
    },
    "212-vip-black-eau-de-parfum": {
        "sku": "PAR-H-039",
        "slug": "212-vip-black-eau-de-parfum",
        "nombre": "212 VIP Black Eau de Parfum",
        "marca": "Carolina Herrera",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Parfum",
        "descripcion": "Una fougère dulce y nocturna con absenta, anís e hinojo, un corazón de lavanda y una base de vainilla negra y almizcle.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 2017,
        "perfumista": "Carlos Benaim | Anne Flipo",
        "notasSalida": "Absenta | Anís | Hinojo",
        "notasCorazon": "Lavanda",
        "notasFondo": "Vainilla negra | Almizcle",
        "acordesPrincipales": "Aromático | Avainillado | Anisado | Lavanda | Dulce",
        "duracion": "7–9 horas",
        "proyeccion": "Alta durante 2–3 horas",
        "estaciones": "Otoño | Invierno",
        "ocasiones": "Fiesta | Discoteca | Citas",
        "estilo": "Nocturno, dulce y atrevido",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Carolina-Herrera/212-VIP-Black-46593.html"
    },
    "boss-bottled-eau-de-toilette": {
        "sku": "PAR-H-040",
        "slug": "boss-bottled-eau-de-toilette",
        "nombre": "Boss Bottled Eau de Toilette",
        "marca": "Hugo Boss",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Un clásico amaderado especiado con manzana, ciruela y cítricos; canela y caoba en el corazón; y vainilla, sándalo, cedro y vetiver en el fondo.",
        "familiaOlfativa": "Amaderada Especiada",
        "anoLanzamiento": 1998,
        "perfumista": "Annick Menardo | Christian Dussoulier",
        "notasSalida": "Manzana | Ciruela | Limón | Bergamota | Musgo de roble | Geranio",
        "notasCorazon": "Canela | Caoba | Clavel",
        "notasFondo": "Vainilla | Sándalo | Cedro | Vetiver | Olivo",
        "acordesPrincipales": "Cálido especiado | Frutal | Amaderado | Canela | Avainillado",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Otoño | Invierno | Primavera",
        "ocasiones": "Oficina | Diario | Reuniones",
        "estilo": "Clásico, profesional y cálido",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Hugo-Boss/Boss-Bottled-383.html"
    },
    "hugo-just-different-eau-de-toilette": {
        "sku": "PAR-H-041",
        "slug": "hugo-just-different-eau-de-toilette",
        "nombre": "Hugo Just Different Eau de Toilette",
        "marca": "Hugo Boss",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una aromática verde con menta y manzana Granny Smith, seguida por albahaca, fresia y cilantro, y un fondo de cashmeran, pachulí, ládano e incienso.",
        "familiaOlfativa": "Aromática",
        "anoLanzamiento": 2011,
        "perfumista": "",
        "notasSalida": "Menta | Manzana Granny Smith",
        "notasCorazon": "Albahaca | Fresia | Cilantro",
        "notasFondo": "Cashmeran | Pachulí | Ládano | Incienso",
        "acordesPrincipales": "Verde | Aromático | Fresco especiado | Frutal | Amaderado",
        "duracion": "4–6 horas",
        "proyeccion": "Moderada a suave durante 1–2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Diario | Oficina | Universidad",
        "estilo": "Verde, casual y diferente",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Hugo-Boss/Hugo-Just-Different-15140.html"
    },
    "blue-jeans-eau-de-toilette": {
        "sku": "PAR-H-042",
        "slug": "blue-jeans-eau-de-toilette",
        "nombre": "Blue Jeans Eau de Toilette",
        "marca": "Versace",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una fougère aromática de estilo noventero con cítricos, lavanda, flores, especias, vainilla, tonka, sándalo, almizcle y maderas. Compleja, dulce y desenfadada.",
        "familiaOlfativa": "Aromática Fougère",
        "anoLanzamiento": 1994,
        "perfumista": "Jean-Pierre Bethouart",
        "notasSalida": "Cítricos | Bergamota | Enebro | Anís | Albahaca | Palo de rosa",
        "notasCorazon": "Lavanda | Rosa | Clavel | Heliotropo | Jazmín | Geranio | Salvia | Abeto",
        "notasFondo": "Vainilla | Haba tonka | Sándalo | Iris | Almizcle | Ámbar | Vetiver | Cedro | Pachulí",
        "acordesPrincipales": "Aromático | Lavanda | Cítrico | Avainillado | Fresco especiado",
        "duracion": "5–7 horas",
        "proyeccion": "Moderada durante 1–2 horas",
        "estaciones": "Primavera | Otoño | Invierno",
        "ocasiones": "Diario | Casual | Salidas",
        "estilo": "Retro, juvenil y versátil",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Versace/Blue-Jeans-637.html"
    },
    "nautica-voyage-eau-de-toilette": {
        "sku": "PAR-H-043",
        "slug": "nautica-voyage-eau-de-toilette",
        "nombre": "Nautica Voyage Eau de Toilette",
        "marca": "Nautica",
        "categoria": "Diseñador",
        "genero": "Hombre",
        "concentracion": "Eau de Toilette",
        "descripcion": "Una fragancia acuática sencilla y refrescante. Hojas verdes y manzana conducen a loto y mimosa, con un fondo limpio de almizcle, cedro, musgo y ámbar.",
        "familiaOlfativa": "Amaderada Acuática",
        "anoLanzamiento": 2006,
        "perfumista": "Maurice Roucel",
        "notasSalida": "Hojas verdes | Manzana",
        "notasCorazon": "Loto | Mimosa",
        "notasFondo": "Almizcle | Cedro | Musgo de roble | Ámbar",
        "acordesPrincipales": "Verde | Acuático | Fresco | Frutal | Ozónico",
        "duracion": "4–6 horas",
        "proyeccion": "Suave a moderada durante 1–2 horas",
        "estaciones": "Primavera | Verano",
        "ocasiones": "Diario | Gimnasio | Clima cálido",
        "estilo": "Ligero, fresco y casual",
        "fuenteReferencia": "https://www.fragrantica.es/perfume/Nautica/Nautica-Voyage-913.html"
    }
};
    const aliases = {
    "valentino-born-in-roma-intense": "valentino-uomo-born-in-roma-intense",
    "scandal-le-parfum": "scandal-pour-homme-le-parfum",
    "valentino-born-in-roma-eau-de-toilette": "valentino-uomo-born-in-roma-eau-de-toilette",
    "valentino-born-in-roma-coral-fantasy": "valentino-uomo-born-in-roma-coral-fantasy",
    "valentino-born-in-roma-green-stravaganza": "valentino-uomo-born-in-roma-green-stravaganza",
    "one-million-gold": "million-gold",
    "acqua-di-gio-profondo": "acqua-di-gio-profondo-eau-de-parfum",
    "the-most-wanted-intense": "the-most-wanted-eau-de-parfum-intense",
    "ultramale": "ultra-male",
    "just-different-eau-de-parfum": "hugo-just-different-eau-de-toilette",
    "blue-jeans-eau-de-parfum": "blue-jeans-eau-de-toilette"
};
    window.PARFUM_DETAILS = catalog;
    window.ParfumDetails = {
        get(reference) {
            const key = String(reference || "").trim().toLowerCase();
            return catalog[key] || catalog[aliases[key]] || null;
        },
        merge(product, reference) {
            const local = this.get(product?.slug || reference);
            if (!local) return product || {};
            const merged = {...local, ...(product || {})};
            for (const [key, value] of Object.entries(local)) {
                if (merged[key] == null || merged[key] === "") merged[key] = value;
            }
            return merged;
        },
        all: catalog
    };
})();
